//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// FoodProject.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FOODPROJECT_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_SIGNUP               132
#define IDD_CHOICE                      134
#define IDD_PAY                         136
#define IDB_SWEETPOTATO                 145
#define IDB_BUL                         146
#define IDB_COMBI                       147
#define IDB_PEP                         148
#define IDB_SOY                         149
#define IDB_GANGJUNG                    150
#define IDB_SEASONING                   151
#define IDB_FRIED                       152
#define IDB_RICE                        153
#define IDB_JJA                         154
#define IDB_JJAM                        155
#define IDB_TANG                        156
#define IDB_BOSSAM                      157
#define IDB_BULZOK                      158
#define IDB_SEASONZOK                   159
#define IDB_ZOK                         160
#define IDB_CARD                        161
#define IDB_BITMAP2                     162
#define IDB_CASH                        162
#define IDD_OPTION1                     163
#define IDD_OPTION2                     165
#define IDD_OPTION3                     167
#define IDB_BONE                        171
#define IDB_BITMAP3                     172
#define IDB_BONELESS                    172
#define IDD_DIALOG_REVISE               173
#define IDD_DIALOG_BILL                 175
#define IDD_DIALOG1                     177
#define IDC_EDIT_ID                     1000
#define IDC_EDIT_PW                     1001
#define IDC_BUTT_LOGIN                  1002
#define IDC_BUTT_SIGNUP                 1003
#define IDC_BUTT_OK                     1004
#define IDC_EDIT_CUSTOMID               1005
#define IDC_EDIT_CUSTOMPW               1006
#define IDC_EDIT_CHECKPW                1007
#define IDC_EDIT_NAME                   1008
#define IDC_EDIT_NAME2                  1009
#define IDC_EDIT_ADDRESS                1009
#define IDC_CHICKEN                     1009
#define IDC_PIZZA                       1010
#define IDC_JOKBO                       1011
#define IDC_CFOOD                       1012
#define IDC_PAYMENT                     1013
#define IDC_LIST_MENU                   1014
#define IDC_CHIK1                       1015
#define IDC_CHIK2                       1016
#define IDC_CHIK3                       1017
#define IDC_CHIK4                       1018
#define IDC_PIZ1                        1019
#define IDC_PIZ2                        1020
#define IDC_PIZ3                        1021
#define IDC_PIZ4                        1022
#define IDC_JK1                         1023
#define IDC_JB1                         1023
#define IDC_JK2                         1024
#define IDC_JB2                         1024
#define IDC_JK3                         1025
#define IDC_JB3                         1025
#define IDC_JK4                         1026
#define IDC_JB4                         1026
#define IDC_CF1                         1027
#define IDC_CF2                         1028
#define IDC_CF3                         1029
#define IDC_CF4                         1030
#define IDC_EDIT_TOTAL                  1031
#define IDC_CARD                        1032
#define IDC_PAY                         1033
#define IDC_COMBO1                      1034
#define IDC_BUTTON1                     1035
#define IDC_BONELESS                    1036
#define IDC_NOMAL                       1037
#define IDC_BUTTON2                     1038
#define IDC_EDIT1                       1039
#define IDC_PRICE                       1039
#define IDC_EDIT2                       1040
#define IDC_BUTT_REVISE                 1040
#define IDC_EDIT3                       1041
#define IDC_LIST1                       1041
#define IDC_EDIT4                       1042
#define IDC_BUTT_BILL                   1042
#define IDC_EDIT5                       1043
#define IDC_BUTT_CHANGEPRICE            1043
#define IDC_EDIT6                       1044
#define IDC_BUTT_HOME                   1044
#define IDC_EDIT7                       1045
#define IDC_BUTT_LOGOUT                 1045
#define IDC_EDIT8                       1046
#define IDC_EDIT9                       1047
#define IDC_BUTT_CANCEL                 1047
#define IDC_EDIT10                      1048
#define IDC_BUTT_EXIT                   1048
#define IDC_EDIT11                      1049
#define IDC_EDIT12                      1050
#define IDC_EDIT13                      1051
#define IDC_EDIT14                      1052
#define IDC_EDIT15                      1053
#define IDC_EDIT16                      1054
#define ID_32771                        32771
#define ID_32772                        32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1049
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
